/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigos_informe_2;

import com.sun.awt.AWTUtilities;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author Lulo
 */
public class Interfaz extends javax.swing.JFrame {
    protected double varianza;
    protected double desviacion_e;
    protected double media;
    protected int tamaño;
    protected int [] arreglo;
    protected String cadena;
    protected char caracter;
    protected double [] arreglo2;
    
    
    public Interfaz() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btn1num_menu = new javax.swing.JButton();
        btn1txt_menu = new javax.swing.JButton();
        btn2num_menu = new javax.swing.JButton();
        btn2txt_menu = new javax.swing.JButton();
        btn3num_menu = new javax.swing.JButton();
        btn3txt_menu = new javax.swing.JButton();
        btn4num_menu = new javax.swing.JButton();
        btn4txt_menu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(300, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(37, 77, 113));
        jPanel1.setPreferredSize(new java.awt.Dimension(300, 70));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ink Free", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MENU");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 200, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 130));

        jPanel2.setBackground(new java.awt.Color(246, 247, 251));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn1num_menu.setFont(new java.awt.Font("Ink Free", 0, 36)); // NOI18N
        btn1num_menu.setForeground(new java.awt.Color(255, 255, 255));
        btn1num_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_interfaz/Btn1_menu.png"))); // NOI18N
        btn1num_menu.setText("1");
        btn1num_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn1num_menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn1num_menu.setMaximumSize(new java.awt.Dimension(101, 70));
        btn1num_menu.setMinimumSize(new java.awt.Dimension(101, 70));
        btn1num_menu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_interfaz/Btn1_menu_pres.png"))); // NOI18N
        btn1num_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1num_menuActionPerformed(evt);
            }
        });
        jPanel2.add(btn1num_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 70, 70));

        btn1txt_menu.setBackground(new java.awt.Color(255, 255, 255));
        btn1txt_menu.setFont(new java.awt.Font("Segoe Print", 0, 16)); // NOI18N
        btn1txt_menu.setText("<html> Calcular media, varianza o desviacion <html>");
        btn1txt_menu.setContentAreaFilled(false);
        btn1txt_menu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn1txt_menu.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn1txt_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1txt_menuActionPerformed(evt);
            }
        });
        jPanel2.add(btn1txt_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 290, 70));

        btn2num_menu.setFont(new java.awt.Font("Ink Free", 0, 36)); // NOI18N
        btn2num_menu.setForeground(new java.awt.Color(255, 255, 255));
        btn2num_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_interfaz/Btn2_menu.png"))); // NOI18N
        btn2num_menu.setText("2");
        btn2num_menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn2num_menu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_interfaz/Btn2_menu_pres.png"))); // NOI18N
        btn2num_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2num_menuActionPerformed(evt);
            }
        });
        jPanel2.add(btn2num_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 70, 70));

        btn2txt_menu.setBackground(new java.awt.Color(255, 255, 255));
        btn2txt_menu.setFont(new java.awt.Font("Segoe Print", 0, 16)); // NOI18N
        btn2txt_menu.setText("<html> Reemplazar vocales por el caracter más repetido <html>");
        btn2txt_menu.setContentAreaFilled(false);
        btn2txt_menu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn2txt_menu.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn2txt_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2txt_menuActionPerformed(evt);
            }
        });
        jPanel2.add(btn2txt_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 290, 70));

        btn3num_menu.setFont(new java.awt.Font("Ink Free", 0, 36)); // NOI18N
        btn3num_menu.setForeground(new java.awt.Color(255, 255, 255));
        btn3num_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_interfaz/Btn3_menu.png"))); // NOI18N
        btn3num_menu.setText("3");
        btn3num_menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn3num_menu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_interfaz/Btn3_menu_pres.png"))); // NOI18N
        btn3num_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3num_menuActionPerformed(evt);
            }
        });
        jPanel2.add(btn3num_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 70, 70));

        btn3txt_menu.setBackground(new java.awt.Color(255, 255, 255));
        btn3txt_menu.setFont(new java.awt.Font("Segoe Print", 0, 16)); // NOI18N
        btn3txt_menu.setText("<html> Ordenar un arreglo <html>");
        btn3txt_menu.setContentAreaFilled(false);
        btn3txt_menu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn3txt_menu.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn3txt_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3txt_menuActionPerformed(evt);
            }
        });
        jPanel2.add(btn3txt_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 290, 70));

        btn4num_menu.setFont(new java.awt.Font("Ink Free", 0, 36)); // NOI18N
        btn4num_menu.setForeground(new java.awt.Color(255, 255, 255));
        btn4num_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_interfaz/Btn1_menu.png"))); // NOI18N
        btn4num_menu.setText("4");
        btn4num_menu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn4num_menu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_interfaz/Btn1_menu_pres.png"))); // NOI18N
        btn4num_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4num_menuActionPerformed(evt);
            }
        });
        jPanel2.add(btn4num_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 70, 70));

        btn4txt_menu.setBackground(new java.awt.Color(255, 255, 255));
        btn4txt_menu.setFont(new java.awt.Font("Segoe Print", 0, 16)); // NOI18N
        btn4txt_menu.setText("<html> Crear personas con nombre, edad y cedula <html>");
        btn4txt_menu.setContentAreaFilled(false);
        btn4txt_menu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn4txt_menu.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btn4txt_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4txt_menuActionPerformed(evt);
            }
        });
        jPanel2.add(btn4txt_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 290, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 400, 420));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn1num_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1num_menuActionPerformed
        punto1 n1= new punto1(this, false);
        n1.setVisible(true);
    }//GEN-LAST:event_btn1num_menuActionPerformed

    private void btn2num_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2num_menuActionPerformed
        punto2 n2= new punto2(this, false);
        n2.setVisible(true);
    }//GEN-LAST:event_btn2num_menuActionPerformed

    private void btn3txt_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3txt_menuActionPerformed
        punto3 n1= new punto3(this, false);
        n1.setVisible(true);
    }//GEN-LAST:event_btn3txt_menuActionPerformed

    private void btn1txt_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1txt_menuActionPerformed
        punto1 n1= new punto1(this, false);
        n1.setVisible(true);
    }//GEN-LAST:event_btn1txt_menuActionPerformed

    private void btn2txt_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2txt_menuActionPerformed
        punto2 n1= new punto2(this, false);
        n1.setVisible(true);
    }//GEN-LAST:event_btn2txt_menuActionPerformed

    private void btn3num_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3num_menuActionPerformed
        punto3 n1= new punto3(this, false);
        n1.setVisible(true);
    }//GEN-LAST:event_btn3num_menuActionPerformed

    private void btn4num_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4num_menuActionPerformed
        punto4 n1= new punto4(this, false);
        n1.setVisible(true);
    }//GEN-LAST:event_btn4num_menuActionPerformed

    private void btn4txt_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4txt_menuActionPerformed
        punto4 n1= new punto4(this, false);
        n1.setVisible(true);
    }//GEN-LAST:event_btn4txt_menuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn1num_menu;
    private javax.swing.JButton btn1txt_menu;
    private javax.swing.JButton btn2num_menu;
    private javax.swing.JButton btn2txt_menu;
    private javax.swing.JButton btn3num_menu;
    private javax.swing.JButton btn3txt_menu;
    private javax.swing.JButton btn4num_menu;
    private javax.swing.JButton btn4txt_menu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
