/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigos_informe_2;

/**
 *
 * @author Lulo
 */
public class punto2 extends javax.swing.JDialog {

    protected String cadena;
    
    
    public punto2(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        Ingresar_texto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        caracter_repetido = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mostrarr = new javax.swing.JTextPane();
        veces = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Print", 0, 24)); // NOI18N
        jLabel1.setText("Ingrese la cadena de texto:");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(246, 247, 251), null, null));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 350, 50));

        aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_interfaz/btn_aceptar.png"))); // NOI18N
        aceptar.setText("ACEPTAR");
        aceptar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        aceptar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_interfaz/btn_aceptar_pres.png"))); // NOI18N
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });
        jPanel2.add(aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 110, 40));

        Ingresar_texto.setBackground(new java.awt.Color(246, 247, 251));
        Ingresar_texto.setFont(new java.awt.Font("Segoe Print", 0, 16)); // NOI18N
        Ingresar_texto.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        Ingresar_texto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 188, 179)));
        Ingresar_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ingresar_textoActionPerformed(evt);
            }
        });
        jPanel2.add(Ingresar_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 380, 80));

        jLabel5.setFont(new java.awt.Font("Segoe Print", 0, 21)); // NOI18N
        jLabel5.setText("Veces repetidas:");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(246, 247, 251), null, null));
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 220, 40));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jLabel2.setText("Caracter más repetido:");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(246, 247, 251), null, null));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 220, 40));

        caracter_repetido.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jPanel2.add(caracter_repetido, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 60, 40));

        jLabel4.setFont(new java.awt.Font("Segoe Print", 0, 21)); // NOI18N
        jLabel4.setText("La nueva cadena es:");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(246, 247, 251), null, null));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 220, 40));

        mostrarr.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jScrollPane1.setViewportView(mostrarr);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 420, 320, 100));

        veces.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        jPanel2.add(veces, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 310, 60, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes_interfaz/fondo_p2.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        aceptar.addActionListener((e) -> {
            char caracter=0;
            cadena=Ingresar_texto.getText();
            cadena=cadena.toLowerCase();
            int contador=0;
            String nueva=cadena;
            while (cadena.length() != 0) {
                int contadorAux = 0;
                for (int j = 0; j < cadena.length(); j++) {
                    if (cadena.charAt(0) == cadena.charAt(j)) {
                        contadorAux++;
                    }
                }
                if (contadorAux > contador) {
                    contador = contadorAux;
                    caracter = cadena.charAt(0);
                    
                }
                cadena = cadena.replaceAll(cadena.charAt(0) + "", "");
            }

            caracter_repetido.setText(Character.toString(caracter));
            veces.setText(Integer.toString(contador));

            nueva = nueva.replace('a',caracter).replace('e',caracter).replace('i',caracter).replace('o',caracter).replace('u',caracter);

            mostrarr.setText(nueva);
        });
    }//GEN-LAST:event_aceptarActionPerformed

    private void Ingresar_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ingresar_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ingresar_textoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(punto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(punto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(punto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(punto2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                punto2 dialog = new punto2(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ingresar_texto;
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel caracter_repetido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane mostrarr;
    private javax.swing.JLabel veces;
    // End of variables declaration//GEN-END:variables
}
